// fetch products actions
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'

// filter products actions
export const FILTER_PRODUCTS_START = 'FILTER_PRODUCTS_START'
export const FILTER_PRODUCTS_SUCCESS = 'FILTER_PRODUCTS_SUCCESS'
export const FILTER_PRODUCTS_FAIL = 'FILTER_PRODUCTS_FAIL'

// filter product actions
export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_FAIL = 'FETCH_PRODUCT_FAIL'

// filter categories actions
export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL'

// cart products actions
export const GET_ITEMS_OF_CART_START = 'GET_ITEMS_OF_CART_START'
export const GET_ITEMS_OF_CART_SUCCESS = 'GET_ITEMS_OF_CART_SUCCESS'
export const GET_ITEMS_OF_CART_FAIL = 'GET_ITEMS_OF_CART_FAIL'
export const GET_ITEMS_COUNT_OF_CART = 'GET_ITEMS_COUNT_OF_CART'
export const ADD_ITEM_CART_SUCCESS = 'ADD_ITEM_CART_SUCCESS'

// filter category actions
export const FETCH_CATEGORIE_START = 'FETCH_CATEGORIE_START'
export const FETCH_CATEGORIE_SUCCESS = 'FETCH_CATEGORIE_SUCCESS'
export const FETCH_CATEGORIE_FAIL = 'FETCH_CATEGORIE_FAIL'

// dummy pages actions
export const FETCH_DUMMY_PAGES_START = 'FETCH_DUMMY_PAGES_START'
export const FETCH_DUMMY_PAGES_SUCCESS = 'FETCH_DUMMY_PAGES_SUCCESS'
export const FETCH_DUMMY_PAGES_FAIL = 'FETCH_DUMMY_PAGES_FAIL'

// register user actions
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

// login user actions
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'
export const LOGOUT_USER = 'LOGOUT_USER'

// user profile actions
export const GET_USER_PROFILE_START = 'GET_USER_PROFILE_START'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL'
export const UPDATE_USER_PROFILE_SUCCESS ='UPDATE_USER_PROFILE_SUCCESS'

// wishlist actions
export const GET_WISHLIST_COUNT = 'GET_WISHLIST_COUNT'
export const GET_WISHLIST_ITEMS = 'GET_WISHLIST_ITEMS'
export const GET_WISHLIST_ID = 'GET_WISHLIST_ID'
export const DELETE_WISHLIST_ITEM = 'DELETE_WISHLIST_ITEM'
export const ADD_WISHLIST_ITEM = 'ADD_WISHLIST_ITEM'

//search by actions
export const GET_SEARCH_BY_PRODUCTS_START = 'GET_SEARCH_BY_PRODUCTS_START'
export const GET_SEARCH_BY_PRODUCTS_SUCCESS = 'GET_SEARCH_BY_PRODUCTS_SUCCESS'
export const GET_SEARCH_BY_LISTS_SUCCESS = 'GET_SEARCH_BY_LISTS_SUCCESS'
export const GET_SEARCH_BY_PRODUCTS_FAIL = 'GET_SEARCH_BY_PRODUCTS_FAIL'

//user address actions
export const GET_ADDRESS_START = 'GET_ADDRESS_START'
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS'
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS'
export const GET_ADDRESS_FAIL = 'GET_ADDRESS_FAIL'

//user checkout actions
export const GET_CHECKOUT_START = 'GET_CHECKOUT_START'
export const GET_CHECKOUT_SUCCESS = 'GET_CHECKOUT_SUCCESS'
export const GET_CHECKOUT_FAIL = 'GET_CHECKOUT_FAIL'
export const GET_ORDER_LISTS_SUCCESS = 'GET_ORDER_LISTS_SUCCESS'

//user checkout actions
export const SEND_SUBSCRIBE_FAIL = 'SEND_SUBSCRIBE_FAIL'
export const SEND_SUBSCRIBE_SUCCESS = 'SEND_SUBSCRIBE_SUCCESS'
export const SEND_SUBSCRIBE_STRAT = 'SEND_SUBSCRIBE_STRAT'



